- name: install packages default to lab in host
  yum:  
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - curl
    - wget 
    - vim 
    - yum-utils
    - git
    - net-tools
    - mariadb
    - mariadb-server 
    - MySQL-python

- name: started packages 
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - madriadb

- name:   
  shell: "systemctl status htttpd | sed -n 3p | awk '/active/ {print $2}' ; systemctl status mariadb | sed -n 3p | awk '/active/ {print $2}'"
  register: service_status

- name: check start
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - mariadb
  when: service_status.stdout == "inactive"       
            